---
title: "HW5Part6"
author: "Eric Rothman"
date: "March 15, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r part d}
thetaMLE = 73/95
p1 = (1 - thetaMLE)*(1 - thetaMLE)
p2 = 2*thetaMLE*(1-thetaMLE)
p3 = thetaMLE * thetaMLE
multinom<-rmultinom(1000,190,c(p1,p2,p3))
y<-rep(0,1000)
for(i in 1:1000) {y[i]<-((2*multinom[3,i]+multinom[2,i])/(2*190))}
hist(y)
sy<-sort(y)
varTheta<-var(y)
varDif<-abs(varTheta-0.000468)
standardError <- sqrt(varTheta)
stdDif<-abs(standardError-0.02164)
print(paste("Bootstrapped variance is", varTheta))
print(paste("This is a difference of ", varDif, "from my asymptotic variance 0.000468"))
print(paste("Bootstrappd standard error is:", standardError))
```

```{r part e}
z<-rep(0,1000)
for(i in 1:1000) {z[i]<-(sy[i]-thetaMLE)}
upperBound<-thetaMLE-z[5]
lowerBound<-thetaMLE-z[995]
print(paste("Confidence interval is (", upperBound, ", ", lowerBound, ")"))
print(paste("Compared by my estimated interval of (0.8241, 0.7127) we get:"))
lowerBoundDiff<-abs(lowerBound - 0.7127)
upperBoundDiff<-abs(upperBound - 0.8241)
print(paste("Lower bounds have a difference of ", lowerBoundDiff))
print(paste("Upper bounds have a difference of ", upperBoundDiff))
```
