---
title: "HW10"
author: "Eric Rothman"
date: "May 2, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r Problem4:question11}

A <- c(rnorm(100,0,1) + 6 - 3 - 2, rnorm(100,0,1) + 6 - 3, rnorm(100,0,1) + 6 - 3 + 2)
B <- c(rnorm(100,0,1) + 6 - 1 - 2, rnorm(100,0,1) + 6 - 1, rnorm(100,0,1) + 6 - 1 + 2)
C <- c(rnorm(100,0,1) + 6 + 1 - 2, rnorm(100,0,1) + 6 + 1, rnorm(100,0,1) + 6 + 1 + 2)
D <- c(rnorm(100,0,1) + 6 + 3 - 2, rnorm(100,0,1) + 6 + 3, rnorm(100,0,1) + 6 + 3 + 2)
ABCD <- c(A,B,C,D)
At<-rep("A",300)
Bt<-rep("B",300)
Ct<-rep("C",300)
Dt<-rep("D",300)
Col<-c(At,Bt,Ct,Dt)
I <- rep("I",100)
II <- rep("II",100)
III <- rep("III",100)
comb <- c(I,II,III)
Row <- rep(comb, 4)
Row_by_Col <- data.frame(ABCD,Col,Row)
output_ANOVA <- aov(ABCD ~Col * Row,data=Row_by_Col)
summary(output_ANOVA)
TukeyHSD(output_ANOVA)
interaction.plot(x.factor=Col, trace.factor=Row,response=ABCD, fun=mean, type="b", legend=T,ylab="Mean Entry", main="Interaction Plot for Output of cols vs row",pch=c(1,19))
```

```{r Prob4:question12}

A <- c(rnorm(100,0,1) + 2 + 1, rnorm(100,0,1) + 2 - 1)
B <- c(rnorm(100,0,1) + 2, rnorm(100,0,1) + 2)
C <- c(rnorm(100,0,1) + 2 - 1, rnorm(100,0,1) + 2 + 1)
ABC <- c(A,B,C)
At<-rep("A",200)
Bt<-rep("B",200)
Ct<-rep("C",200)
Col<-c(At,Bt,Ct)
I <- rep("I",100)
II <- rep("II",100)
comb <- c(I,II)
Row <- rep(comb, 3)
Row_by_Col <- data.frame(ABC,Col,Row)
output_ANOVA <- aov(ABC ~Col * Row,data=Row_by_Col)
summary(output_ANOVA)
TukeyHSD(output_ANOVA)
interaction.plot(x.factor=Col, trace.factor=Row,response=ABC, fun=mean, type="b", legend=T,ylab="Mean Entry", main="Interaction Plot for Output of cols vs row",pch=c(1,19))
```

```{r prob6:question21}
Group1_worm<-c(279,338,334,198,303)
Group2_worm<-c(378,275,412,265,286)
Group3_worm<-c(172,335,335,282,250)
Group4_worm<-c(381,346,340,471,318)
GR1<-rep("Group 1",5)
GR2<-rep("Group 2",5)
GR3<-rep("Group 3",5)
GR4<-rep("Group 4",5)
GroupTot<-c(Group1_worm,Group2_worm,Group3_worm,Group4_worm)
Group<-c(GR1,GR2,GR3,GR4)
wormCount_by_Group<-data.frame(GroupTot,Group)
plot(GroupTot~Group, data=wormCount_by_Group)
print("So it looks like the variance for Group 4 is bigger.")
worm_ANOVA<-aov(GroupTot~Group, data=wormCount_by_Group)
summary(worm_ANOVA)
print("The F test only gives a p value of 0.12, which isn't significant.")
TukeyHSD(worm_ANOVA)
```

```{r prob7:question34a}
TreatmentA<-c(3.1,4.5,4.6,4.3,3.6,2.9,4.0,2.3,2.2,2.1,1.8,2.3)
TreatmentB<-c(8.2,11.0,8.8,7.2,9.2,6.1,4.9,12.4,3.0,3.7,3.8,2.9)
TreatmentC<-c(4.3,4.5,6.3,7.6,4.4,3.5,3.1,4.0,2.3,2.5,2.4,2.2)
TreatmentD<-c(4.5,7.1,6.6,6.2,5.6,10.0,7.1,3.8,3.0,3.6,3.1,3.3)
SurvivalHours<-c(TreatmentA,TreatmentB,TreatmentC,TreatmentD)
A<-rep("A",12)
B<-rep("B",12)
C<-rep("C",12)
D<-rep("D",12)
Treatments<-c(A,B,C,D)
poison1<-rep("I", 4)
poison2<-rep("II", 4)
poison3<-rep("III",4)
poison4<-c(poison1,poison2,poison3)
Poisons <-rep(poison4, 4)
Survival_by_Treatment<-data.frame(SurvivalHours,Treatments,Poisons)
Survival_ANOVA<-aov(SurvivalHours ~Treatments * Poisons, data=Survival_by_Treatment)
summary(Survival_ANOVA)
TukeyHSD(Survival_ANOVA)
interaction.plot(x.factor=Treatments, trace.factor=Poisons,
response=SurvivalHours, fun=mean, type="b", legend=T,
ylab="Hours Survived", main="Interaction Plot for Output by Poisons and Treatements",
pch=c(1,19))
print("As is clear to see from the graph, the small p-values, and the Tukey test, there is both interaction and main effects for the data.")
print("The largest affect seems to be between treatments A and B")
```

```{r prob11:40PartAandB}
Load<-c(1,2,3,4,5,6,7,8,9,10)
totalLoad<-rep(Load,3)
Run1<-c(68.32,136.78,204.98,273.85,342.7,411.3,480.65,549.85,619,688.7)
Run2<-c(68.35,136.68,205.02,273.85,342.63,411.35,480.6,549.85,619.02,688.62)
Run3<-c(68.3,136.8,204.98,273.80,342.63,411.28,480.63,549.83,619.1,688.58)
Residuals<-c(Run1,Run2,Run3)
print("PART A:")
plot(totalLoad,Residuals,main="Load versus Deflection",xlab="The load in 10000's",ylab="The deflection")
print("The plot does look linear. Note that the difference between runs is small enough compared to the range of the data that while 3 points for each load were plotted, it looks like only 1 was.")

print("PART B:")
Regression_Load_Residuals<-lm(Residuals ~ totalLoad)
summary(Regression_Load_Residuals)
plot(Regression_Load_Residuals)
plot(totalLoad,Residuals,main="Load versus Deflection",xlab="The load in 10000's",ylab="The deflection")
abline(-1.46844,68.02172)
print("For the left half of the data, the line fits well, as the load increases, the data starts to curve up a little bit. So it appears that a straight line will not fully fit the data, so there is a little systematic lack of fit.")
```